version: '3'
services:
  backend:
    build: backend
    depends_on:
      - database
    environment:
      - PGURI=postgres://postgres:${POSTGRES_PASSWORD}@database/postgres
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
  database:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:13
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    volumes:
      - ./data:/var/lib/postgresql/data
