services:
  backend:
    build: backend
    depends_on:
      - database
    environment:
      - PGURI=postgres://postgres:${POSTGRES_PASSWORD}@database/postgres
    ports:
      - "3000:3000"
  database:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:13
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
  frontend:
    build: frontend
    ports: 
      - "80:80"
    restart: always
    depends_on:
      - backend